- id: algo-visualization
  en: Algorithm visualization.
  zh: 算法可视化。
  link: https://algo.lexcao.io

- id: kox
  en: Kotlin implementation of Lox language.
  zh: 用 Kotlin 实现的 Lox 编程语言。
  link: https://github.com/lexcao/kox

- id: konverter
  en: Code generation for converter between data class by KAPT.
  zh: 通过 KAPT 生成 data class 自动转换代码。
  link: https://github.com/lexcao/konverter
