# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'diabled-disqus'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
  en: 
  - {uid: 'archive', path: 'menu', url: 'archive.html'}
  - {uid: 'about', path: 'menu', url: 'about.html'}
  zh:
  - {uid: 'archive', path: 'zh/menu', url: 'archive.html'}
  - {uid: 'about', path: 'zh/menu', url: 'about.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com'}
- {icon: 'twitter', link: 'https://twitter.com'}
- {icon: 'weibo', link: 'https://www.weibo.com'}
- {icon: 'envelope', link: 'mailto:clixin@foxmail.com'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}