# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'diabled-disqus'

menu:
  en: 
  - {uid: 'archive', path: 'menu', url: 'archive.html'}
  - {uid: 'about', path: 'menu', url: 'about.html'}
  zh:
  - {uid: 'archive', path: 'zh/menu', url: 'archive.html'}
  - {uid: 'about', path: 'zh/menu', url: 'about.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {show: true, icon: 'github', link: 'https://github.com/lexcao'}
- {show: true, icon: 'twitter', link: 'https://twitter.com/lexcao'}
- {show: false, icon: 'weibo', link: 'https://weibo.com'}
- {show: true, icon: 'envelope', link: 'mailto:lexcao@foxmail.com'}
- {show: false, icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}
