# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'disabled-disqus'

menu:
  en:
  - {uid: 'archive', path: 'menu', url: 'archive.html'}
  - {uid: 'project', path: 'menu', url: 'project.html'}
  - {uid: 'about', path: 'menu', url: 'about.html'}
  zh:
  - {uid: 'archive', path: 'zh/menu', url: 'archive.html'}
  - {uid: 'project', path: 'zh/menu', url: 'project.html'}
  - {uid: 'about', path: 'zh/menu', url: 'about.html'}

social:
- {show: true, icon: 'github', link: 'https://github.com/lexcao'}
- {show: true, icon: 'twitter', link: 'https://twitter.com/lexcao'}
- {show: true, icon: 'envelope', link: 'mailto:lexcao@foxmail.com'}
- {show: false, icon: 'rss-square', link: '/feed.xml'}
